### ISSUE TITLE
Feature suggestion: Add optional where part for for-loops

### ISSUE THREAD

**Issue by chack05** [yasl-lang/yasl#153]
Like this:

```
for x <- [1, 2, 3, 4, 5, 6] where x % 2 === 0 {
     echo x
}
```

It consists of an additional keyword where followed by an expression. It's basically syntactic sugar for

```
for x <- [1, 2, 3, 4, 5, 6] {
    if x % 2 !== 0 {
        continue
    } 
    echo x
}
```

or

```
for x <- [1, 2, 3, 4, 5, 6] {
    if x % 2 === 0 {
        echo x
    } 
}
```

Languages that had implemented this before: OpenEdge ABL

Costs/challenges of implementing said feature: None known.

Apparently I can't add labels, so consider this a feature request.

**Comment by CoffeeTableEspresso** [comment]
I've added the labels for you. (And will see about making it so people can add their own labels.)

I'll comment properly on your two feature-requests when I've got some time this evening.

**Comment by CoffeeTableEspresso** [comment]
I likely won't implement this, since you can achieve the same thing with 2 extra characters (the `{` and `}` for the `if`).

If I were to implement this, I would re-use the `if` keyword, to match the syntax supported by list comprehensions (instead of adding a new `where` keyword):
`[ f(x) for x <- [1, 2, 3, 4, 5, 6] if x % 2 === 0 ]`.
